import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ta' | 'hi';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  en: {
    // App
    'app.name': 'MyArea',
    'app.tagline': 'Connecting Citizens with Their Community',
    
    // Language Selection
    'language.select': 'Select Your Language',
    'language.choose': 'Choose your preferred language',
    'language.continue': 'Continue',
    'language.english': 'English',
    'language.tamil': 'தமிழ்',
    'language.hindi': 'हिंदी',
    
    // Auth Choice
    'auth.welcome': 'Welcome to MyArea',
    'auth.chooseOption': 'Please choose an option to continue',
    'auth.login': 'Log In',
    'auth.loginDesc': 'Already have an account',
    'auth.signup': 'Sign Up',
    'auth.signupDesc': 'Create a new account',
    
    // Auth Page
    'auth.enterCredentials': 'Enter your credentials to continue',
    'auth.createAccount': 'Create your account to get started',
    'auth.phone': 'Phone',
    'auth.email': 'Email',
    'auth.phoneNumber': 'Phone Number',
    'auth.emailAddress': 'Email Address',
    'auth.password': 'Password',
    'auth.enterPassword': 'Enter your password',
    'auth.sendOtp': 'Send OTP',
    'auth.back': 'Back',
    'auth.verifyOtp': 'Verify OTP',
    'auth.otpSentTo': 'Enter the 6-digit code sent to',
    'auth.yourPhone': 'your phone',
    'auth.yourEmail': 'your email',
    'auth.resendOtp': 'Resend OTP',
    'auth.resendIn': 'Resend in',
    'auth.seconds': 'seconds',
    'auth.enterOtp': 'Enter OTP',
    
    // Password Validation
    'password.strength': 'Password Strength',
    'password.weak': 'Weak',
    'password.medium': 'Medium',
    'password.strong': 'Strong',
    'password.requirements': 'Password Requirements',
    'password.minLength': 'At least 8 characters',
    'password.maxLength': 'Maximum 20 characters',
    'password.uppercase': 'One uppercase letter',
    'password.lowercase': 'One lowercase letter',
    'password.number': 'One number',
    'password.special': 'One special character (@#$%&!)',
    'password.noSpaces': 'No spaces allowed',
    'password.showPassword': 'Show password',
    'password.hidePassword': 'Hide password',
    
    // Validation Messages
    'validation.required': 'This field is required',
    'validation.nameMinLength': 'Minimum 2 characters required',
    'validation.nameAlphabetic': 'Only alphabetic characters allowed',
    'validation.ageRequired': 'Age is required',
    'validation.ageNumber': 'Age must be a number',
    'validation.ageRange': 'Age must be between 18 and 100',
    'validation.pincodeRequired': 'Pincode is required',
    'validation.pincodeSixDigits': 'Pincode must be exactly 6 digits',
    'validation.phoneRequired': 'Phone number is required',
    'validation.phoneTenDigits': 'Phone number must be 10 digits',
    'validation.emailRequired': 'Email is required',
    'validation.emailInvalid': 'Invalid email format',
    'validation.relationRequired': 'Relation is required',
    'validation.emergencyContactRequired': 'At least one emergency contact is required',
    'validation.businessNameRequired': 'Business name is required',
    'validation.businessNameMinLength': 'Minimum 3 characters required',
    'validation.descriptionMaxLength': 'Maximum 250 characters allowed',
    'validation.consentRequired': 'You must agree to be contacted',
    'validation.helpDescMinLength': 'Minimum 10 characters required',
    
    // Profile Completion
    'profile.complete': 'Complete Your Profile',
    'profile.helpServe': 'Help us serve you better',
    'profile.basicInfo': 'Basic Information',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.age': 'Age',
    'profile.gender': 'Gender',
    'profile.genderOptional': 'Gender (Optional)',
    'profile.selectGender': 'Select',
    'profile.male': 'Male',
    'profile.female': 'Female',
    'profile.other': 'Other',
    'profile.preferNotToSay': 'Prefer not to say',
    'profile.address': 'Address',
    'profile.houseFlatNo': 'House / Flat No',
    'profile.street': 'Street',
    'profile.area': 'Area',
    'profile.wardSector': 'Ward / Sector Number',
    'profile.city': 'City',
    'profile.pincode': 'Pincode',
    'profile.volunteerInterest': 'Volunteer Interest',
    'profile.willingToVolunteer': 'Are you willing to volunteer in your community?',
    'profile.yes': 'Yes',
    'profile.no': 'No',
    'profile.areasOfInterest': 'Areas of Interest:',
    'profile.emergencyContacts': 'Emergency Contacts',
    'profile.addContact': 'Add Contact',
    'profile.noContactsYet': 'No emergency contacts added yet',
    'profile.name': 'Name',
    'profile.relation': 'Relation',
    'profile.servicesProvided': 'Services Provided',
    'profile.provideServices': 'Do you provide any community services? (Optional)',
    'profile.serviceType': 'Service Type',
    'profile.selectServiceType': 'Select service type',
    'profile.businessName': 'Business / Service Name',
    'profile.workPhone': 'Office / Work Phone Number',
    'profile.serviceArea': 'Service Area',
    'profile.description': 'Description',
    'profile.submitProfile': 'Submit Profile',
    
    // Verification Status
    'verification.pending': 'Verification Pending',
    'verification.underReview': 'Your account is currently under verification by the Municipality. This process typically takes 24-48 hours.',
    'verification.notification': 'You will receive a notification once your account is verified.',
    'verification.statusPending': 'Status: Pending',
    'verification.continueDemo': 'Continue (Demo)',
    'verification.verified': 'Verified!',
    'verification.success': 'Your account has been successfully verified by the Municipality. You can now access all features of MyArea.',
    'verification.welcome': 'Welcome to the MyArea community!',
    'verification.goToHome': 'Go to Home',
    
    // Home Page
    'home.wardSector': 'Ward / Sector',
    'home.priorityAlerts': 'Priority Alerts',
    'home.viewDetails': 'View details',
    'home.services': 'Services',
    'home.notices': 'Notices',
    'home.noticesDesc': 'Official announcements',
    'home.helpVolunteer': 'Help / Volunteer',
    'home.helpVolunteerDesc': 'Community support',
    'home.servicesTitle': 'Services',
    'home.servicesDesc': 'Local service providers',
    'home.safety': 'Safety',
    'home.safetyDesc': 'Emergency & alerts',
    'home.emergencySos': 'Emergency SOS',
    'home.sosDesc': 'Send immediate alert to municipality and emergency contacts',
    'home.sendSosAlert': 'SEND SOS ALERT',
    'home.confirmEmergency': 'Confirm Emergency Alert',
    'home.sosConfirmation': 'Do you want to send an emergency alert? This will notify the municipality and your emergency contacts.',
    'home.cancel': 'Cancel',
    'home.yesSend': 'Yes, Send Alert',
    'home.home': 'Home',
    'home.polls': 'Polls',
    'home.profile': 'Profile',
    'home.alertSent': 'Alert Sent Successfully!',
    'home.alertSentDesc': 'Your emergency alert has been sent to the municipality and your emergency contacts.',
    'home.backToHome': 'Back to Home',
    
    // Notices
    'notices.title': 'Notices',
    'notices.subtitle': 'Official announcements and updates',
    'notices.postedBy': 'Posted by:',
    'notices.viewPdf': 'View PDF',
    'notices.download': 'Download',
    'notices.close': 'Close',
    'notices.pdfDownloadMsg': 'PDF download started',
    'notices.importantNote': 'Important Note',
    'notices.noteContent': 'All residents are requested to take note of this announcement and plan accordingly.',
    'notices.additionalInfo': 'Additional Information',
    'notices.info1': 'For queries, contact the municipal office',
    'notices.info2': 'This notice is effective immediately',
    'notices.info3': 'Updates will be posted on the MyArea portal',
    'notices.issuedBy': 'Issued By',
    'notices.issueDate': 'Issue Date',
    'notices.reference': 'Reference No',
    'notices.officialSeal': 'Official Municipal Seal',
    'notices.date': 'Date',
    
    // Notice Detail
    'noticeDetail.title': 'Notice Details',
    'noticeDetail.back': 'Back to Notices',
    
    // Help & Volunteer
    'help.title': 'Help & Volunteer',
    'help.subtitle': 'Support and connect with your community',
    'help.needHelp': 'Need Help',
    'help.offerHelp': 'Offer Help',
    'help.events': 'Events',
    'help.requestHelp': 'Request Help',
    'help.requestDesc': 'Describe what kind of help you need and the community will respond.',
    'help.typeOfHelp': 'Type of Help',
    'help.selectType': 'Select type',
    'help.describeNeed': 'Describe your need in detail...',
    'help.submitRequest': 'Submit Request',
    'help.offerHelpTitle': 'Offer Help',
    'help.offerDesc': 'Share what kind of help you can provide to the community.',
    'help.helpCategory': 'Help Category',
    'help.availability': 'Availability (Optional)',
    'help.description': 'Description',
    'help.describeOffer': 'Describe what help you can provide...',
    'help.consentText': 'I agree to be contacted by community members',
    'help.shareOffer': 'Share My Offer',
    'help.notifyText': 'You will be notified when someone nearby needs your help.',
    'help.upcomingEvents': 'Upcoming Volunteer Events',
    'help.showDetails': 'Show Details',
    'help.joinEvent': 'Join Event',
    'help.joined': 'Joined',
    'help.requestSent': 'Request Sent Successfully!',
    'help.requestSentDesc': 'Your request has been sent to the community.',
    'help.offerShared': 'Offer Shared Successfully!',
    'help.offerSharedDesc': 'Your offer has been shared with the community.',
    'help.backToHelp': 'Back to Help & Volunteer',
    
    // Event Detail
    'event.title': 'Event Details',
    'event.back': 'Back to Events',
    'event.dateTime': 'Date & Time',
    'event.location': 'Location',
    'event.organizer': 'Organizer',
    'event.description': 'Description',
    'event.joinEvent': 'Join Event',
    'event.joined': 'Joined',
    'event.confirmJoin': 'Confirm Registration',
    'event.joinConfirmation': 'Do you want to register for this event?',
    'event.cancel': 'Cancel',
    'event.confirm': 'Yes, Join Event',
    'event.registrationSuccess': 'Registration Successful!',
    'event.registrationSuccessDesc': 'You have successfully registered for this event.',
    'event.ok': 'OK',
    
    // Services
    'services.title': 'Services',
    'services.subtitle': 'Local service providers in your area',
    'services.nearby': 'Nearby Services',
    'services.callNow': 'Call Now',
    'services.viewDetails': 'View Details',
    'services.showMore': 'More',
    'services.showLess': 'Less',
    'services.noServices': 'No services available in this category',
    
    // Service Detail
    'serviceDetail.title': 'Service Details',
    'serviceDetail.back': 'Back to Services',
    'serviceDetail.owner': 'Owner',
    'serviceDetail.phone': 'Phone',
    'serviceDetail.hours': 'Working Hours',
    'serviceDetail.location': 'Location',
    'serviceDetail.description': 'Description',
    'serviceDetail.callNow': 'Call Now',
    
    // Safety
    'safety.title': 'Safety & Emergency',
    'safety.subtitle': 'Emergency contacts and safety alerts',
    'safety.emergencyNumbers': 'Emergency Numbers',
    'safety.tapToCall': 'Tap to call',
    'safety.safetyAlerts': 'Safety Alerts',
    'safety.moreDetails': 'More Details',
    'safety.safetyTips': 'Safety Tips',
    'safety.tip1': 'Keep emergency numbers saved in your phone',
    'safety.tip2': 'Stay informed about local alerts and warnings',
    'safety.tip3': 'Follow municipality guidelines during emergencies',
    'safety.tip4': 'Report suspicious activities to local authorities',
    'safety.viewMore': 'View More',
    
    // Alert Detail
    'alert.title': 'Alert Details',
    'alert.back': 'Back to Safety',
    'alert.issuedBy': 'Issued by',
    'alert.severity': 'Severity',
    'alert.high': 'High',
    'alert.medium': 'Medium',
    'alert.low': 'Low',
    'alert.description': 'Description',
    'alert.instructions': 'Instructions',
    
    // Polls
    'polls.title': 'Community Polls',
    'polls.subtitle': 'Have your say in community decisions',
    'polls.active': 'Active',
    'polls.expired': 'Expired',
    'polls.closed': 'Closed',
    'polls.clickToVote': 'Click an option to vote',
    'polls.youVoted': '✓ You voted on this poll',
    'polls.totalVotes': 'Total votes:',
    'polls.votes': 'votes',
    'polls.endsIn': 'Ends in',
    'polls.expiresOn': 'Expires on',
    'polls.days': 'days',
    'polls.winner': 'Winner',
    'polls.noActivePolls': 'No active polls at the moment',
    'polls.noExpiredPolls': 'No expired polls',
    
    // Profile
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your account and settings',
    'profile.yearsOld': 'years old',
    'profile.address': 'Address',
    'profile.emergencyContacts': 'Emergency Contacts',
    'profile.volunteerInterests': 'Volunteer Interests',
    'profile.serviceProvided': 'Service Provided',
    'profile.settings': 'Settings',
    'profile.language': 'Language',
    'profile.changeLanguage': 'Change Language',
    'profile.aboutLegal': 'About & Legal',
    'profile.aboutMyArea': 'About MyArea',
    'profile.about': 'About MyArea',
    'profile.privacy': 'Privacy Policy',
    'profile.terms': 'Terms & Conditions',
    'profile.support': 'Support',
    'profile.helpSupport': 'Help & Support',
    'profile.logout': 'Logout',
    'profile.logoutConfirm': 'Are you sure you want to logout?',
    'profile.helpSupport': 'Help & Support',
    'profile.faqs': 'FAQs',
    'profile.logout': 'Logout',
    'profile.version': 'MyArea v1.0.0',
    
    // About Page
    'about.title': 'About MyArea',
    'about.whatIs': 'What is MyArea?',
    'about.description': 'MyArea is a government-supported digital platform designed to connect residents with their local community and municipality. The application enables access to official notices, emergency alerts, community help, verified services, and volunteer opportunities within your ward or sector.',
    'about.mission': 'Our Mission',
    'about.missionDesc': 'MyArea aims to improve safety, transparency, and civic participation for citizens of all age groups.',
    'about.back': 'Back to Profile',
    
    // Privacy Page
    'privacy.title': 'Privacy Policy',
    'privacy.dataCollection': 'Data Collection',
    'privacy.dataCollectionDesc': 'We collect only essential personal information.',
    'privacy.dataUsage': 'Data Usage',
    'privacy.dataUsageDesc': 'Data is used solely for community safety and service delivery.',
    'privacy.dataSharing': 'Data Sharing',
    'privacy.dataSharingDesc': 'No data is sold to third parties.',
    'privacy.emergencyInfo': 'Emergency Information',
    'privacy.emergencyInfoDesc': 'Emergency information is shared only during alerts.',
    'privacy.protection': 'Data Protection',
    'privacy.protectionDesc': 'All data is protected under applicable data protection laws.',
    'privacy.back': 'Back to Profile',
    
    // Terms Page
    'terms.title': 'Terms & Conditions',
    'terms.accuracy': 'Accuracy',
    'terms.accuracyDesc': 'Users must provide accurate information.',
    'terms.misuse': 'Misuse',
    'terms.misuseDesc': 'Misuse of SOS or false alerts may lead to suspension.',
    'terms.verification': 'Verification',
    'terms.verificationDesc': 'Municipality reserves the right to verify or reject accounts.',
    'terms.services': 'Services',
    'terms.servicesDesc': 'Services listed are community-provided, not government guarantees.',
    'terms.back': 'Back to Profile',
    
    // Help & Support Page
    'helpSupport.title': 'Help & Support',
    'helpSupport.faqs': 'Frequently Asked Questions',
    'helpSupport.q1': 'How long does verification take?',
    'helpSupport.a1': 'Usually 1-2 business days.',
    'helpSupport.q2': 'Who can see my information?',
    'helpSupport.a2': 'Only municipality administrators and relevant community members during emergencies.',
    'helpSupport.q3': 'Can I change my language later?',
    'helpSupport.a3': 'Yes, from Profile → Settings → Change Language.',
    'helpSupport.q4': 'What happens if I press SOS by mistake?',
    'helpSupport.a4': 'You will be asked to confirm before sending.',
    'helpSupport.q5': 'Are service providers verified?',
    'helpSupport.a5': 'Services are community-listed and subject to moderation.',
    'helpSupport.back': 'Back to Profile',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.submit': 'Submit',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.ok': 'OK',
    'common.or': 'or',
  },
  ta: {
    // App
    'app.name': 'மைஏரியா',
    'app.tagline': 'குடிமக்களை அவர்களின் சமூகத்துடன் இணைக்கிறது',
    
    // Language Selection
    'language.select': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    'language.choose': 'உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
    'language.continue': 'தொடரவும்',
    'language.english': 'English',
    'language.tamil': 'தமிழ்',
    'language.hindi': 'हिंदी',
    
    // Auth Choice
    'auth.welcome': 'மைஏரியாவுக்கு வரவேற்கிறோம்',
    'auth.chooseOption': 'தொடர ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்',
    'auth.login': 'உள்நுழைய',
    'auth.loginDesc': 'ஏற்கனவே கணக்கு உள்ளது',
    'auth.signup': 'பதிவு செய்ய',
    'auth.signupDesc': 'புதிய கணக்கை உருவாக்கவும்',
    
    // Auth Page
    'auth.enterCredentials': 'தொடர உங்கள் விவரங்களை உள்ளிடவும்',
    'auth.createAccount': 'தொடங்க உங்கள் கணக்கை உருவாக்கவும்',
    'auth.phone': 'தொலைபேசி',
    'auth.email': 'மின்னஞ்சல்',
    'auth.phoneNumber': 'தொலைபேசி எண்',
    'auth.emailAddress': 'மின்னஞ்சல் முகவரி',
    'auth.password': 'கடவுச்சொல்',
    'auth.enterPassword': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    'auth.sendOtp': 'OTP அனுப்பவும்',
    'auth.back': 'பின்செல்',
    'auth.verifyOtp': 'OTP சரிபார்க்கவும்',
    'auth.otpSentTo': '6 இலக்க குறியீட்டை உள்ளிடவும்',
    'auth.yourPhone': 'உங்கள் தொலைபேசி',
    'auth.yourEmail': 'உங்கள் மின்னஞ்சல்',
    'auth.resendOtp': 'OTP மீண்டும் அனுப்பவும்',
    'auth.resendIn': 'மீண்டும் அனுப்பவும்',
    'auth.seconds': 'விநாடிகள்',
    'auth.enterOtp': 'OTP உள்ளிடவும்',
    
    // Password Validation
    'password.strength': 'கடவுச்சொல் வலிமை',
    'password.weak': 'பலவீனமான',
    'password.medium': 'நடுத்தர',
    'password.strong': 'வலுவான',
    'password.requirements': 'கடவுச்சொல் தேவைகள்',
    'password.minLength': 'குறைந்தது 8 எழுத்துக்கள்',
    'password.maxLength': 'அதிகபட்சம் 20 எழுத்துக்கள்',
    'password.uppercase': 'ஒரு பெரிய எழுத்து',
    'password.lowercase': 'ஒரு சிறிய எழுத்து',
    'password.number': 'ஒரு எண்',
    'password.special': 'ஒரு சிறப்பு எழுத்து (@#$%&!)',
    'password.noSpaces': 'இடைவெளிகள் அனுமதிக்கப்படவில்லை',
    'password.showPassword': 'கடவுச்சொல்லைக் காட்டு',
    'password.hidePassword': 'கடவுச்சொல்லை மறை',
    
    // Validation Messages
    'validation.required': 'இந்த புலம் தேவை',
    'validation.nameMinLength': 'குறைந்தது 2 எழுத்துக்கள் தேவை',
    'validation.nameAlphabetic': 'எழுத்துக்கள் மட்டுமே அனுமதிக்கப்படும்',
    'validation.ageRequired': 'வயது தேவை',
    'validation.ageNumber': 'வயது ஒரு எண்ணாக இருக்க வேண்டும்',
    'validation.ageRange': 'வயது 18 முதல் 100 வரை இருக்க வேண்டும்',
    'validation.pincodeRequired': 'அஞ்சல் குறியீடு தேவை',
    'validation.pincodeSixDigits': 'அஞ்சல் குறியீடு சரியாக 6 இலக்கங்களாக இருக்க வேண்டும்',
    'validation.phoneRequired': 'தொலைபேசி எண் தேவை',
    'validation.phoneTenDigits': 'தொலைபேசி எண் 10 இலக்கங்களாக இருக்க வேண்டும்',
    'validation.emailRequired': 'மின்னஞ்சல் தேவை',
    'validation.emailInvalid': 'தவறான மின்னஞ்சல் வடிவம்',
    'validation.relationRequired': 'உறவு தேவை',
    'validation.emergencyContactRequired': 'குறைந்தது ஒரு அவசர தொடர்பு தேவை',
    'validation.businessNameRequired': 'வணிக பெயர் தேவை',
    'validation.businessNameMinLength': 'குறைந்தது 3 எழுத்துக்கள் தேவை',
    'validation.descriptionMaxLength': 'அதிகபட்சம் 250 எழுத்துக்கள் அனுமதிக்கப்படும்',
    'validation.consentRequired': 'நீங்கள் தொடர்பு கொள்ள ஒப்புக்கொள்ள வேண்டும்',
    'validation.helpDescMinLength': 'குறைந்தது 10 எழுத்துக்கள் தேவை',
    
    // Profile Completion
    'profile.complete': 'உங்கள் சுயவிவரத்தை முடிக்கவும்',
    'profile.helpServe': 'உங்களுக்கு சிறப்பாக சேவை செய்ய எங்களுக்கு உதவவும்',
    'profile.basicInfo': 'அடிப்படை தகவல்',
    'profile.firstName': 'முதல் பெயர்',
    'profile.lastName': 'கடைசி பெயர்',
    'profile.age': 'வயது',
    'profile.gender': 'பாலினம்',
    'profile.genderOptional': 'பாலினம் (விருப்பமானது)',
    'profile.selectGender': 'தேர்ந்தெடுக்கவும்',
    'profile.male': 'ஆண்',
    'profile.female': 'பெண்',
    'profile.other': 'மற்றவை',
    'profile.preferNotToSay': 'சொல்ல விரும்பவில்லை',
    'profile.address': 'முகவரி',
    'profile.houseFlatNo': 'வீடு / குடியிருப்பு எண்',
    'profile.street': 'தெரு',
    'profile.area': 'பகுதி',
    'profile.wardSector': 'வார்டு / துறை எண்',
    'profile.city': 'நகரம்',
    'profile.pincode': 'அஞ்சல் குறியீடு',
    'profile.volunteerInterest': 'தன்னார்வ ஆர்வம்',
    'profile.willingToVolunteer': 'உங்கள் சமூகத்தில் தன்னார்வத் தொண்டு செய்ய விருப்பமா?',
    'profile.yes': 'ஆம்',
    'profile.no': 'இல்லை',
    'profile.areasOfInterest': 'ஆர்வமுள்ள பகுதிகள்:',
    'profile.emergencyContacts': 'அவசர தொடர்புகள்',
    'profile.addContact': 'தொடர்பைச் சேர்க்கவும்',
    'profile.noContactsYet': 'இன்னும் அவசர தொடர்புகள் சேர்க்கப்படவில்லை',
    'profile.name': 'பெயர்',
    'profile.relation': 'உறவு',
    'profile.servicesProvided': 'வழங்கப்படும் சேவைகள்',
    'profile.provideServices': 'நீங்கள் ஏதேனும் சமூக சேவைகளை வழங்குகிறீர்களா? (விருப்பமானது)',
    'profile.serviceType': 'சேவை வகை',
    'profile.selectServiceType': 'சேவை வகையைத் தேர்ந்தெடுக்கவும்',
    'profile.businessName': 'வணிகம் / சேவை பெயர்',
    'profile.workPhone': 'அலுவலகம் / பணி தொலைபேசி எண்',
    'profile.serviceArea': 'சேவைப் பகுதி',
    'profile.description': 'விளக்கம்',
    'profile.submitProfile': 'சுயவிவரத்தை சமர்ப்பிக்கவும்',
    
    // Verification Status
    'verification.pending': 'சரிபார்ப்பு நிலுவையில் உள்ளது',
    'verification.underReview': 'உங்கள் கணக்கு தற்போது நகராட்சியால் சரிபார்க்கப்படுகிறது. இந்த செயல்முறை பொதுவாக 24-48 மணிநேரம் ஆகும்.',
    'verification.notification': 'உங்கள் கணக்கு சரிபார்க்கப்பட்டதும் அறிவிப்பு பெறுவீர்கள்.',
    'verification.statusPending': 'நிலை: நிலுவையில்',
    'verification.continueDemo': 'தொடரவும் (டெமோ)',
    'verification.verified': 'சரிபார்க்கப்பட்டது!',
    'verification.success': 'உங்கள் கணக்கு நகராட்சியால் வெற்றிகரமாக சரிபார்க்கப்பட்டது. இப்போது மைஏரியாவின் அனைத்து அம்சங்களையும் அணுகலாம்.',
    'verification.welcome': 'மைஏரியா சமூகத்திற்கு வரவேற்கிறோம்!',
    'verification.goToHome': 'முகப்புக்குச் செல்லவும்',
    
    // Home Page
    'home.wardSector': 'வார்டு / துறை',
    'home.priorityAlerts': 'முன்னுரிமை எச்சரிக்கைகள்',
    'home.viewDetails': 'விவரங்களைக் காண்க',
    'home.services': 'சேவைகள்',
    'home.notices': 'அறிவிப்புகள்',
    'home.noticesDesc': 'அதிகாரப்பூர்வ அறிவிப்புகள்',
    'home.helpVolunteer': 'உதவி / தன்னார்வம்',
    'home.helpVolunteerDesc': 'சமூக ஆதரவு',
    'home.servicesTitle': 'சேவைகள்',
    'home.servicesDesc': 'உள்ளூர் சேவை வழங்குநர்கள்',
    'home.safety': 'பாதுகாப்பு',
    'home.safetyDesc': 'அவசரநிலை & எச்சரிக்கைகள்',
    'home.emergencySos': 'அவசர SOS',
    'home.sosDesc': 'நகராட்சி மற்றும் அவசர தொடர்புகளுக்கு உடனடி எச்சரிக்கை அனுப்பவும்',
    'home.sendSosAlert': 'SOS எச்சரிக்கை அனுப்பவும்',
    'home.confirmEmergency': 'அவசர எச்சரிக்கையை உறுதிப்படுத்தவும்',
    'home.sosConfirmation': 'அவசர எச்சரிக்கையை அனுப்ப விரும்புகிறீர்களா? இது நகராட்சி மற்றும் உங்கள் அவசர தொடர்புகளுக்கு அறிவிக்கும்.',
    'home.cancel': 'ரத்துசெய்',
    'home.yesSend': 'ஆம், எச்சரிக்கை அனுப்பவும்',
    'home.home': 'முகப்பு',
    'home.polls': 'கருத்துக்கணிப்புகள்',
    'home.profile': 'சுயவிவரம்',
    'home.alertSent': 'எச்சரிக்கை வெற்றிகரமாக அனுப்பப்பட்டது!',
    'home.alertSentDesc': 'உங்கள் அவசர எச்சரிக்கை நகராட்சி மற்றும் உங்கள் அவசர தொடர்புகளுக்கு அனுப்பப்பட்டது.',
    'home.backToHome': 'முகப்புக்குத் திரும்பு',
    
    // Notices
    'notices.title': 'அறிவிப்புகள்',
    'notices.subtitle': 'அதிகாரப்பூர்வ அறிவிப்புகள் மற்றும் புதுப்பிப்புகள்',
    'notices.postedBy': 'இடுகையிட்டவர்:',
    'notices.viewPdf': 'PDF காண்க',
    'notices.download': 'பதிவிறக்கம்',
    'notices.close': 'மூடு',
    'notices.pdfDownloadMsg': 'PDF பதிவிறக்கம் தொடங்கியது',
    'notices.importantNote': 'முக்கிய குறிப்பு',
    'notices.noteContent': 'அனைத்து குடியிருப்பாளர்களும் இந்த அறிவிப்பை கவனித்து அதற்கேற்ப திட்டமிட வேண்டும்.',
    'notices.additionalInfo': 'கூடுதல் தகவல்',
    'notices.info1': 'கேள்விகளுக்கு, நகராட்சி அலுவலகத்தை தொடர்பு கொள்ளவும்',
    'notices.info2': 'இந்த அறிவிப்பு உடனடியாக நடைமுறைக்கு வருகிறது',
    'notices.info3': 'புதுப்பிப்புகள் மைஏரியா போர்ட்டலில் இடுகையிடப்படும்',
    'notices.issuedBy': 'வெளியிட்டவர்',
    'notices.issueDate': 'வெளியீட்டு தேதி',
    'notices.reference': 'குறிப்பு எண்',
    'notices.officialSeal': 'அதிகாரப்பூர்வ நகராட்சி முத்திரை',
    'notices.date': 'தேதி',
    
    // Notice Detail
    'noticeDetail.title': 'அறிவிப்பு விவரங்கள்',
    'noticeDetail.back': 'அறிவிப்புகளுக்குத் திரும்பு',
    
    // Help & Volunteer
    'help.title': 'உதவி & தன்னார்வம்',
    'help.subtitle': 'உங்கள் சமூகத்துடன் ஆதரவு மற்றும் இணைப்பு',
    'help.needHelp': 'உதவி தேவை',
    'help.offerHelp': 'உதவி வழங்கவும்',
    'help.events': 'நிகழ்வுகள்',
    'help.requestHelp': 'உதவி கோரவும்',
    'help.requestDesc': 'உங்களுக்கு என்ன உதவி தேவை என்பதை விவரிக்கவும், சமூகம் பதிலளிக்கும்.',
    'help.typeOfHelp': 'உதவி வகை',
    'help.selectType': 'வகையைத் தேர்ந்தெடுக்கவும்',
    'help.describeNeed': 'உங்கள் தேவையை விரிவாக விவரிக்கவும்...',
    'help.submitRequest': 'கோரிக்கையை சமர்ப்பிக்கவும்',
    'help.offerHelpTitle': 'உதவி வழங்கவும்',
    'help.offerDesc': 'நீங்கள் சமூகத்திற்கு என்ன உதவி வழங்க முடியும் என்பதைப் பகிரவும்.',
    'help.helpCategory': 'உதவி வகை',
    'help.availability': 'கிடைக்கும் தன்மை (விருப்பமானது)',
    'help.description': 'விளக்கம்',
    'help.describeOffer': 'நீங்கள் என்ன உதவி வழங்க முடியும் என்பதை விவரிக்கவும்...',
    'help.consentText': 'சமூக உறுப்பினர்களால் தொடர்பு கொள்ள ஒப்புக்கொள்கிறேன்',
    'help.shareOffer': 'எனது வாய்ப்பைப் பகிரவும்',
    'help.notifyText': 'உங்களுக்கு அருகில் யாருக்காவது உங்கள் உதவி தேவைப்படும் போது அறிவிக்கப்படுவீர்கள்.',
    'help.upcomingEvents': 'வரவிருக்கும் தன்னார்வ நிகழ்வுகள்',
    'help.showDetails': 'விவரங்களைக் காட்டு',
    'help.joinEvent': 'நிகழ்வில் சேரவும்',
    'help.joined': 'சேர்ந்துள்ளது',
    'help.requestSent': 'கோரிக்கை வெற்றிகரமாக அனுப்பப்பட்டது!',
    'help.requestSentDesc': 'உங்கள் கோரிக்கை சமூகத்திற்கு அனுப்பப்பட்டது.',
    'help.offerShared': 'வாய்ப்பு வெற்றிகரமாகப் பகிரப்பட்டது!',
    'help.offerSharedDesc': 'உங்கள் வாய்ப்பு சமூகத்துடன் பகிரப்பட்டது.',
    'help.backToHelp': 'உதவி & தன்னார்வத்திற்குத் திரும்பு',
    
    // Event Detail
    'event.title': 'நிகழ்வு விவரங்கள்',
    'event.back': 'நிகழ்வுகளுக்குத் திரும்பு',
    'event.dateTime': 'தேதி & நேரம்',
    'event.location': 'இடம்',
    'event.organizer': 'ஏற்பாட்டாளர்',
    'event.description': 'விளக்கம்',
    'event.joinEvent': 'நிகழ்வில் சேரவும்',
    'event.joined': 'சேர்ந்துள்ளது',
    'event.confirmJoin': 'பதிவை உறுதிப்படுத்தவும்',
    'event.joinConfirmation': 'இந்த நிகழ்விற்கு பதிவு செய்ய விரும்புகிறீர்களா?',
    'event.cancel': 'ரத்துசெய்',
    'event.confirm': 'ஆம், நிகழ்வில் சேரவும்',
    'event.registrationSuccess': 'பதிவு வெற்றிகரமானது!',
    'event.registrationSuccessDesc': 'இந்த நிகழ்விற்கு நீங்கள் வெற்றிகரமாக பதிவு செய்துள்ளீர்கள்.',
    'event.ok': 'சரி',
    
    // Services
    'services.title': 'சேவைகள்',
    'services.subtitle': 'உங்கள் பகுதியில் உள்ள உள்ளூர் சேவை வழங்குநர்கள்',
    'services.nearby': 'அருகிலுள்ள சேவைகள்',
    'services.callNow': 'இப்போது அழைக்கவும்',
    'services.viewDetails': 'விவரங்களைக் காண்க',
    'services.showMore': 'மேலும்',
    'services.showLess': 'குறைவாக',
    'services.noServices': 'இந்தப் பிரிவில் சேவைகள் எதுவும் இல்லை',
    
    // Service Detail
    'serviceDetail.title': 'சேவை விவரங்கள்',
    'serviceDetail.back': 'சேவைகளுக்குத் திரும்பு',
    'serviceDetail.owner': 'உரிமையாளர்',
    'serviceDetail.phone': 'தொலைபேசி',
    'serviceDetail.hours': 'வேலை நேரம்',
    'serviceDetail.location': 'இடம்',
    'serviceDetail.description': 'விளக்கம்',
    'serviceDetail.callNow': 'இப்போது அழைக்கவும்',
    
    // Safety
    'safety.title': 'பாதுகாப்பு & அவசரநிலை',
    'safety.subtitle': 'அவசர தொடர்புகள் மற்றும் பாதுகாப்பு எச்சரிக்கைகள்',
    'safety.emergencyNumbers': 'அவசர எண்கள்',
    'safety.tapToCall': 'அழைக்க தட்டவும்',
    'safety.safetyAlerts': 'பாதுகாப்பு எச்சரிக்கைகள்',
    'safety.moreDetails': 'மேலும் விவரங்கள்',
    'safety.safetyTips': 'பாதுகாப்பு குறிப்புகள்',
    'safety.tip1': 'அவசர எண்களை உங்கள் தொலைபேசியில் சேமித்து வைக்கவும்',
    'safety.tip2': 'உள்ளூர் எச்சரிக்கைகள் மற்றும் எச்சரிக்கைகள் பற்றி தெரிந்துகொள்ளுங்கள்',
    'safety.tip3': 'அவசரநிலைகளின் போது நகராட்சி வழிகாட்டுதல்களைப் பின்பற்றவும்',
    'safety.tip4': 'சந்தேகத்திற்குரிய செயல்பாடுகளை உள்ளூர் அதிகாரிகளிடம் தெரிவிக்கவும்',
    'safety.viewMore': 'மேலும் காண்க',
    
    // Alert Detail
    'alert.title': 'எச்சரிக்கை விவரங்கள்',
    'alert.back': 'பாதுகாப்புக்குத் திரும்பு',
    'alert.issuedBy': 'வெளியிட்டவர்',
    'alert.severity': 'தீவிரம்',
    'alert.high': 'உயர்',
    'alert.medium': 'நடுத்தர',
    'alert.low': 'குறைந்த',
    'alert.description': 'விளக்கம்',
    'alert.instructions': 'வழிமுறைகள்',
    
    // Polls
    'polls.title': 'சமூக கருத்துக்கணிப்புகள்',
    'polls.subtitle': 'சமூக முடிவுகளில் உங்கள் கருத்தைச் சொல்லுங்கள்',
    'polls.active': 'செயலில்',
    'polls.expired': 'காலாவதியானது',
    'polls.closed': 'மூடப்பட்டது',
    'polls.clickToVote': 'வாக்கள��க்க ஒரு விருப்பத்தைக் கிளிக் செய்யவும்',
    'polls.youVoted': '✓ இந்த கருத்துக்கணிப்பில் நீங்கள் வாக்களித்துள்ளீர்கள்',
    'polls.totalVotes': 'மொத்த வாக்குகள்:',
    'polls.votes': 'வாக்குகள்',
    'polls.endsIn': 'முடிவடையும் நேரம்',
    'polls.expiresOn': 'காலாவதியாகும் தேதி',
    'polls.days': 'நாட்கள்',
    'polls.winner': 'வெற்றியாளர்',
    'polls.noActivePolls': 'தற்போது செயலில் உள்ள கருத்துக்கணிப்புகள் இல்லை',
    'polls.noExpiredPolls': 'காலாவதியான கருத்துக்கணிப்புகள் இல்லை',
    
    // Profile
    'profile.title': 'சுயவிவரம்',
    'profile.subtitle': 'உங்கள் கணக்கையும் அமைப்புகளையும் நிர்வகிக்கவும்',
    'profile.yearsOld': 'வயது',
    'profile.address': 'முகவரி',
    'profile.emergencyContacts': 'அவசர தொடர்புகள்',
    'profile.volunteerInterests': 'தன்னார்வ ஆர்வங்கள்',
    'profile.serviceProvided': 'வழங்கப்பட்ட சேவை',
    'profile.settings': 'அமைப்புகள்',
    'profile.language': 'மொழி',
    'profile.changeLanguage': 'மொழியை மாற்றவும்',
    'profile.aboutLegal': 'பற்றி & சட்ட',
    'profile.aboutMyArea': 'மைஏரியா பற்றி',
    'profile.about': 'மைஏரியா பற்றி',
    'profile.privacy': 'தனியுரிமைக் கொள்கை',
    'profile.terms': 'விதிமுறைகள் & நிபந்தனைகள்',
    'profile.support': 'ஆதரவு',
    'profile.helpSupport': 'உதவி & ஆதரவு',
    'profile.logout': 'வெளியேறு',
    'profile.logoutConfirm': 'நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
    'profile.helpSupport': 'உதவி & ஆதரவு',
    'profile.faqs': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    'profile.logout': 'வெளியேறு',
    'profile.version': 'மைஏரியா v1.0.0',
    
    // About Page
    'about.title': 'மைஏரியா பற்றி',
    'about.whatIs': 'மைஏரியா என்றால் என்ன?',
    'about.description': 'மைஏரியா என்பது குடியிருப்பாளர்களை அவர்களின் உள்ளூர் சமூகம் மற்றும் நகராட்சியுடன் இணைக்க வடிவமைக்கப்பட்ட அரசாங்க ஆதரவு டிஜிட்டல் தளமாகும். இந்த பயன்பாடு உத்தியோகபூர்வ அறிவிப்புகள், அவசர எச்சரிக்கைகள், சமூக உதவி, சரிபார்க்கப்பட்ட சேவைகள் மற்றும் உங்கள் வார்டு அல்லது துறைக்குள் தன்னார்வ வாய்ப்புகளை அணுக உதவுகிறது.',
    'about.mission': 'எங்கள் நோக்கம்',
    'about.missionDesc': 'மைஏரியா அனைத்து வயதினருக்கும் பாதுகாப்பு, வெளிப்படைத்தன்மை மற்றும் குடிமை பங்கேற்பை மேம்படுத்துவதை நோக்கமாகக் கொண்டுள்ளது.',
    'about.back': 'சுயவிவரத்திற்குத் திரும்பு',
    
    // Privacy Page
    'privacy.title': 'தனியுரிமைக் கொள்கை',
    'privacy.dataCollection': 'தரவு சேகரிப்பு',
    'privacy.dataCollectionDesc': 'நாங்கள் அத்தியாவசிய தனிப்பட்ட தகவல்களை மட்டுமே சேகரிக்கிறோம்.',
    'privacy.dataUsage': 'தரவு பயன்பாடு',
    'privacy.dataUsageDesc': 'தரவு சமூக பாதுகாப்பு மற்றும் சேவை வழங்கலுக்கு மட்டுமே பயன்படுத்தப்படுகிறது.',
    'privacy.dataSharing': 'தரவு பகிர்வு',
    'privacy.dataSharingDesc': 'எந்த தரவும் மூன்றாம் தரப்பினருக்கு விற்கப்படுவதில்லை.',
    'privacy.emergencyInfo': 'அவசர தகவல்',
    'privacy.emergencyInfoDesc': 'அவசர தகவல் எச்சரிக்கைகளின் போது மட்டுமே பகிரப்படுகிறது.',
    'privacy.protection': 'தரவு பாதுகாப்பு',
    'privacy.protectionDesc': 'அனைத்து தரவும் பொருந்தக்கூடிய தரவு பாதுகாப்பு சட்டங்களின் கீழ் பாதுகாக்கப்படுகிறது.',
    'privacy.back': 'சுயவிவரத்திற்குத் திரும்பு',
    
    // Terms Page
    'terms.title': 'விதிமுறைகள் & நிபந்தனைகள்',
    'terms.accuracy': 'துல்லியம்',
    'terms.accuracyDesc': 'பயனர்கள் துல்லியமான தகவல்களை வழங்க வேண்டும்.',
    'terms.misuse': 'தவறான பயன்பாடு',
    'terms.misuseDesc': 'SOS இன் தவறான பயன்பாடு அல்லது தவறான எச்சரிக்கைகள் இடைநிறுத்தத்திற்கு வழிவகுக்கலாம்.',
    'terms.verification': 'சரிபார்ப்பு',
    'terms.verificationDesc': 'நகராட்சிக்கு கணக்குகளை சரிபார்க்க அல்லது நிராகரிக்க உரிமை உள்ளது.',
    'terms.services': 'சேவைகள்',
    'terms.servicesDesc': 'பட்டியலிடப்பட்ட சேவைகள் சமூகம் வழங்கியவை, அரசாங்க உத்தரவாதங்கள் அல்ல.',
    'terms.back': 'சுயவிவரத்திற்குத் திரும்பு',
    
    // Help & Support Page
    'helpSupport.title': 'உதவி & ஆதரவு',
    'helpSupport.faqs': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    'helpSupport.q1': 'சரிபார்ப்பு எவ்வளவு நேரம் ஆகும்?',
    'helpSupport.a1': 'பொதுவாக 1-2 வணிக நாட்கள்.',
    'helpSupport.q2': 'எனது தகவலை யார் பார்க்க முடியும்?',
    'helpSupport.a2': 'அவசரநிலைகளின் போது நகராட்சி நிர்வாகிகள் மற்றும் தொடர்புடைய சமூக உறுப்பினர்கள் மட்டுமே.',
    'helpSupport.q3': 'நான் பின்னர் எனது மொழியை மாற்ற முடியுமா?',
    'helpSupport.a3': 'ஆம், சுயவிவரம் → அமைப்புகள் → மொழியை மாற்றவும்.',
    'helpSupport.q4': 'நான் தவறுதலாக SOS அழுத்தினால் என்ன நடக்கும்?',
    'helpSupport.a4': 'அனுப்புவதற்கு முன் உறுதிப்படுத்த கேட்கப்படுவீர்கள்.',
    'helpSupport.q5': 'சேவை வழங்குநர்கள் சரிபார்க்கப்பட்டவர்களா?',
    'helpSupport.a5': 'சேவைகள் சமூகத்தால் பட்டியலிடப்பட்டவை மற்றும் மதிப்பீட்டிற்கு உட்பட்டவை.',
    'helpSupport.back': 'சுயவிவரத்திற்குத் திரும்பு',
    
    // Common
    'common.loading': 'ஏற்றுகிறது...',
    'common.error': 'பிழை',
    'common.success': 'வெற்றி',
    'common.submit': 'சமர்ப்பிக்கவும்',
    'common.save': 'சேமிக்கவும்',
    'common.edit': 'திருத்தவும்',
    'common.delete': 'நீக்கவும்',
    'common.confirm': 'உறுதிப்படுத்தவும்',
    'common.back': 'பின்செல்',
    'common.close': 'மூடு',
    'common.ok': 'சரி',
    'common.or': 'அல்லது',
  },
  hi: {
    // App
    'app.name': 'मायएरिया',
    'app.tagline': 'नागरिकों को उनके समुदाय से जोड़ना',
    
    // Language Selection
    'language.select': 'अपनी भाषा चुनें',
    'language.choose': 'अपनी पसंदीदा भाषा चुनें',
    'language.continue': 'जारी रखें',
    'language.english': 'English',
    'language.tamil': 'தமிழ்',
    'language.hindi': 'हिंदी',
    
    // Auth Choice
    'auth.welcome': 'मायएरिया में आपका स्वागत है',
    'auth.chooseOption': 'जारी रखने के लिए एक विकल्प चुनें',
    'auth.login': 'लॉग इन',
    'auth.loginDesc': 'पहले से खाता है',
    'auth.signup': 'साइन अप',
    'auth.signupDesc': 'नया खाता बनाएं',
    
    // Auth Page
    'auth.enterCredentials': 'जारी रखने के लिए अपनी जानकारी दर्ज करें',
    'auth.createAccount': 'शुरू करने के लिए अपना खाता बनाएं',
    'auth.phone': 'फोन',
    'auth.email': 'ईमेल',
    'auth.phoneNumber': 'फोन नंबर',
    'auth.emailAddress': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.enterPassword': 'अपना पासवर्ड दर्ज करें',
    'auth.sendOtp': 'OTP भेजें',
    'auth.back': 'वापस',
    'auth.verifyOtp': 'OTP सत्यापित करें',
    'auth.otpSentTo': '6 अंकों का कोड दर्ज करें',
    'auth.yourPhone': 'आपका फोन',
    'auth.yourEmail': 'आपका ईमेल',
    'auth.resendOtp': 'OTP पुनः भेजें',
    'auth.resendIn': 'में पुनः भेजें',
    'auth.seconds': 'सेकंड',
    'auth.enterOtp': 'OTP दर्ज करें',
    
    // Password Validation
    'password.strength': 'पासवर्ड शक्ति',
    'password.weak': 'कमजोर',
    'password.medium': 'मध्यम',
    'password.strong': 'मजबूत',
    'password.requirements': 'पासवर्ड आवश्यकताएं',
    'password.minLength': 'कम से कम 8 अक्षर',
    'password.maxLength': 'अधिकतम 20 अक्षर',
    'password.uppercase': 'एक बड़ा अक्षर',
    'password.lowercase': 'एक छोटा अक्षर',
    'password.number': 'एक संख्या',
    'password.special': 'एक विशेष वर्ण (@#$%&!)',
    'password.noSpaces': 'स्पेस की अनुमति नहीं',
    'password.showPassword': 'पासवर्ड दिखाएं',
    'password.hidePassword': 'पासवर्ड छुपाएं',
    
    // Validation Messages
    'validation.required': 'यह फील्ड आवश्यक है',
    'validation.nameMinLength': 'कम से कम 2 अक्षर आवश्यक',
    'validation.nameAlphabetic': 'केवल वर्णमाला की अनुमति है',
    'validation.ageRequired': 'उम्र आवश्यक है',
    'validation.ageNumber': 'उम्र एक संख्या होनी चाहिए',
    'validation.ageRange': 'उम्र 18 से 100 के बीच होनी चाहिए',
    'validation.pincodeRequired': 'पिनकोड आवश्यक है',
    'validation.pincodeSixDigits': 'पिनकोड ठीक 6 अंकों का होना चाहिए',
    'validation.phoneRequired': 'फोन नंबर आवश्यक है',
    'validation.phoneTenDigits': 'फोन नंबर 10 अंकों का होना चाहिए',
    'validation.emailRequired': 'ईमेल आवश्यक है',
    'validation.emailInvalid': 'अमान्य ईमेल प्रारूप',
    'validation.relationRequired': 'संबंध आवश्यक है',
    'validation.emergencyContactRequired': 'कम से कम एक आपातकालीन संपर्क आवश्यक है',
    'validation.businessNameRequired': 'व्यवसाय का नाम आवश्यक है',
    'validation.businessNameMinLength': 'कम से कम 3 अक्षर आवश्यक',
    'validation.descriptionMaxLength': 'अधिकतम 250 अक्षरों की अनुमति है',
    'validation.consentRequired': 'आपको संपर्क करने के लिए सहमत होना चाहिए',
    'validation.helpDescMinLength': 'कम से कम 10 अक्षर आवश्यक',
    
    // Profile Completion
    'profile.complete': 'अपनी प्रोफाइल पूरी करें',
    'profile.helpServe': 'आपकी बेहतर सेवा करने में हमारी मदद करें',
    'profile.basicInfo': 'मूल जानकारी',
    'profile.firstName': 'पहला नाम',
    'profile.lastName': 'अंतिम नाम',
    'profile.age': 'उम्र',
    'profile.gender': 'लिंग',
    'profile.genderOptional': 'लिंग (वैकल्पिक)',
    'profile.selectGender': 'चुनें',
    'profile.male': 'पुरुष',
    'profile.female': 'महिला',
    'profile.other': 'अन्य',
    'profile.preferNotToSay': 'कहना पसंद नहीं',
    'profile.address': 'पता',
    'profile.houseFlatNo': 'घर / फ्लैट नंबर',
    'profile.street': 'गली',
    'profile.area': 'क्षेत्र',
    'profile.wardSector': 'वार्ड / सेक्टर नंबर',
    'profile.city': 'शहर',
    'profile.pincode': 'पिनकोड',
    'profile.volunteerInterest': 'स्वयंसेवक रुचि',
    'profile.willingToVolunteer': 'क्या आप अपने समुदाय में स्वयंसेवक बनना चाहते हैं?',
    'profile.yes': 'हाँ',
    'profile.no': 'नहीं',
    'profile.areasOfInterest': 'रुचि के क्षेत्र:',
    'profile.emergencyContacts': 'आपातकालीन संपर्क',
    'profile.addContact': 'संपर्क जोड़ें',
    'profile.noContactsYet': 'अभी तक कोई आपातकालीन संपर्क नहीं जोड़ा गया',
    'profile.name': 'नाम',
    'profile.relation': 'संबंध',
    'profile.servicesProvided': 'प्रदान की गई सेवाएं',
    'profile.provideServices': 'क्या आप कोई सामुदायिक सेवाएं प्रदान करते हैं? (वैकल्पिक)',
    'profile.serviceType': 'सेवा प्रकार',
    'profile.selectServiceType': 'सेवा प्रकार चुनें',
    'profile.businessName': 'व्यवसाय / सेवा नाम',
    'profile.workPhone': 'कार्यालय / कार्य फोन नंबर',
    'profile.serviceArea': 'सेवा क्षेत्र',
    'profile.description': 'विवरण',
    'profile.submitProfile': 'प्रोफाइल सबमिट करें',
    
    // Verification Status
    'verification.pending': 'सत्यापन लंबित',
    'verification.underReview': 'आपका खाता वर्तमान में नगर पालिका द्वारा सत्यापन के अधीन है। यह प्रक्रिया आमतौर पर 24-48 घंटे लेती है।',
    'verification.notification': 'आपके खाते के सत्यापित होने पर आपको एक सूचना प्राप्त होगी।',
    'verification.statusPending': 'स्थिति: लंबित',
    'verification.continueDemo': 'जारी रखें (डेमो)',
    'verification.verified': 'सत्यापित!',
    'verification.success': 'आपका खाता नगर पालिका द्वारा सफलतापूर्वक सत्यापित किया गया है। अब आप मायएरिया की सभी सुविधाओं का उपयोग कर सकते हैं।',
    'verification.welcome': 'मायएरिया समुदाय में आपका स्वागत है!',
    'verification.goToHome': 'होम पर जाएं',
    
    // Home Page
    'home.wardSector': 'वार्ड / सेक्टर',
    'home.priorityAlerts': 'प्राथमिकता अलर्ट',
    'home.viewDetails': 'विवरण देखें',
    'home.services': 'सेवाएं',
    'home.notices': 'नोटिस',
    'home.noticesDesc': 'आधिकारिक घोषणाएं',
    'home.helpVolunteer': 'मदद / स्वयंसेवक',
    'home.helpVolunteerDesc': 'सामुदायिक सहायता',
    'home.servicesTitle': 'सेवाएं',
    'home.servicesDesc': 'स्थानीय सेवा प्रदाता',
    'home.safety': 'सुरक्षा',
    'home.safetyDesc': 'आपातकालीन और अलर्ट',
    'home.emergencySos': 'आपातकालीन SOS',
    'home.sosDesc': 'नगर पालिका और आपातकालीन संपर्कों को तत्काल अलर्ट भेजें',
    'home.sendSosAlert': 'SOS अलर्ट भेजें',
    'home.confirmEmergency': 'आपातकालीन अलर्ट की पुष्टि करें',
    'home.sosConfirmation': 'क्या आप आपातकालीन अलर्ट भेजना चाहते हैं? यह नगर पालिका और आपके आपातकालीन संपर्कों को सूचित करेगा।',
    'home.cancel': 'रद्द करें',
    'home.yesSend': 'हाँ, अलर्ट भेजें',
    'home.home': 'होम',
    'home.polls': 'पोल',
    'home.profile': 'प्रोफाइल',
    'home.alertSent': 'अलर्ट सफलतापूर्वक भेजा गया!',
    'home.alertSentDesc': 'आपका आपातकालीन अलर्ट नगर पालिका और आपके आपातकालीन संपर्कों को भेजा गया है।',
    'home.backToHome': 'होम पर वापस जाएं',
    
    // Notices
    'notices.title': 'नोटिस',
    'notices.subtitle': 'आधिकारिक घोषणाएं और अपडेट',
    'notices.postedBy': 'द्वारा पोस्ट किया गया:',
    'notices.viewPdf': 'PDF देखें',
    'notices.download': 'डाउनलोड',
    'notices.close': 'बंद करें',
    'notices.pdfDownloadMsg': 'PDF डाउनलोड शुरू हुआ',
    'notices.importantNote': 'महत्वपूर्ण नोट',
    'notices.noteContent': 'सभी निवासियों से अनुरोध है कि वे इस घोषणा को नोट करें और उसके अनुसार योजना बनाएं।',
    'notices.additionalInfo': 'अतिरिक्त जानकारी',
    'notices.info1': 'प्रश्नों के लिए, नगरपालिका कार्यालय से संपर्क करें',
    'notices.info2': 'यह नोटिस तुरंत प्रभावी है',
    'notices.info3': 'अपडेट मायएरिया पोर्टल पर पोस्ट किए जाएंगे',
    'notices.issuedBy': 'जारीकर्ता',
    'notices.issueDate': 'जारी तिथि',
    'notices.reference': 'संदर्भ संख्या',
    'notices.officialSeal': 'आधिकारिक नगरपालिका मुहर',
    'notices.date': 'तारीख',
    
    // Notice Detail
    'noticeDetail.title': 'नोटिस विवरण',
    'noticeDetail.back': 'नोटिस पर वापस जाएं',
    
    // Help & Volunteer
    'help.title': 'मदद और स्वयंसेवक',
    'help.subtitle': 'अपने समुदाय के साथ समर्थन और जुड़ें',
    'help.needHelp': 'मदद चाहिए',
    'help.offerHelp': 'मदद की पेशकश',
    'help.events': 'इवेंट',
    'help.requestHelp': 'मदद का अनुरोध करें',
    'help.requestDesc': 'बताएं कि आपको किस प्रकार की मदद चाहिए और समुदाय प्रतिक्रिया देगा।',
    'help.typeOfHelp': 'मदद का प्रकार',
    'help.selectType': 'प्रकार चुनें',
    'help.describeNeed': 'अपनी आवश्यकता को विस्तार से बताएं...',
    'help.submitRequest': 'अनुरोध सबमिट करें',
    'help.offerHelpTitle': 'मदद की पेशकश',
    'help.offerDesc': 'बताएं कि आप समुदाय को किस प्रकार की मदद प्रदान कर सकते हैं।',
    'help.helpCategory': 'मदद की श्रेणी',
    'help.availability': 'उपलब्धता (वैकल्पिक)',
    'help.description': 'विवरण',
    'help.describeOffer': 'बताएं कि आप क्या मदद प्रदान कर सकते हैं...',
    'help.consentText': 'मैं समुदाय के सदस्यों द्वारा संपर्क किए जाने के लिए सहमत हूं',
    'help.shareOffer': 'मेरी पेशकश साझा करें',
    'help.notifyText': 'जब आपके पास किसी को आपकी मदद की आवश्यकता होगी तो आपको सूचित किया जाएगा।',
    'help.upcomingEvents': 'आगामी स्वयंसेवक इवेंट',
    'help.showDetails': 'विवरण दिखाएं',
    'help.joinEvent': 'इवेंट में शामिल हों',
    'help.joined': 'शामिल हो गए',
    'help.requestSent': 'अनुरोध सफलतापूर्वक भेजा गया!',
    'help.requestSentDesc': 'आपका अनुरोध समुदाय को भेजा गया है।',
    'help.offerShared': 'पेशकश सफलतापूर्वक साझा की गई!',
    'help.offerSharedDesc': 'आपकी पेशकश समुदाय के साथ साझा की गई है।',
    'help.backToHelp': 'मदद और स्वयंसेवक पर वापस जाएं',
    
    // Event Detail
    'event.title': 'इवेंट विवरण',
    'event.back': 'इवेंट पर वापस जाएं',
    'event.dateTime': 'तारीख और समय',
    'event.location': 'स्थान',
    'event.organizer': 'आयोजक',
    'event.description': 'विवरण',
    'event.joinEvent': 'इवेंट में शामिल हों',
    'event.joined': 'शामिल हो गए',
    'event.confirmJoin': 'पंजीकरण की पुष्टि करें',
    'event.joinConfirmation': 'क्या आप इस इवेंट के लिए पंजीकरण करना चाहते हैं?',
    'event.cancel': 'रद्द करें',
    'event.confirm': 'हाँ, इवेंट में शामिल हों',
    'event.registrationSuccess': 'पंजीकरण सफल!',
    'event.registrationSuccessDesc': 'आपने इस इवेंट के लिए सफलतापूर्वक पंजीकरण किया है।',
    'event.ok': 'ठीक है',
    
    // Services
    'services.title': 'सेवाएं',
    'services.subtitle': 'आपके क्षेत्र में स्थानीय सेवा प्रदाता',
    'services.nearby': 'पास की सेवाएं',
    'services.callNow': 'अभी कॉल करें',
    'services.viewDetails': 'विवरण देखें',
    'services.showMore': 'अधिक',
    'services.showLess': 'कम',
    'services.noServices': 'इस श्रेणी में कोई सेवा उपलब्ध नहीं है',
    
    // Service Detail
    'serviceDetail.title': 'सेवा विवरण',
    'serviceDetail.back': 'सेवाओं पर वापस जाएं',
    'serviceDetail.owner': 'मालिक',
    'serviceDetail.phone': 'फोन',
    'serviceDetail.hours': 'काम के घंटे',
    'serviceDetail.location': 'स्थान',
    'serviceDetail.description': 'विवरण',
    'serviceDetail.callNow': 'अभी कॉल करें',
    
    // Safety
    'safety.title': 'सुरक्षा और आपातकाल',
    'safety.subtitle': 'आपातकालीन संपर्क और सुरक्षा अलर्ट',
    'safety.emergencyNumbers': 'आपातकालीन नंबर',
    'safety.tapToCall': 'कॉल करने के लिए टैप करें',
    'safety.safetyAlerts': 'सुरक्षा अलर्ट',
    'safety.moreDetails': 'अधिक जानकारी',
    'safety.safetyTips': 'सुरक्षा टिप्स',
    'safety.tip1': 'आपातकालीन नंबर अपने फोन में सहेजें',
    'safety.tip2': 'स्थानीय अलर्ट और चेतावनियों के बारे में सूचित रहें',
    'safety.tip3': 'आपात स्थिति के दौरान नगर पालिका दिशानिर्देशों का पालन करें',
    'safety.tip4': 'संदिग्ध गतिविधियों की स्थानीय अधिकारियों को रिपोर्ट करें',
    'safety.viewMore': 'और देखें',
    
    // Alert Detail
    'alert.title': 'अलर्ट विवरण',
    'alert.back': 'सुरक्षा पर वापस जाएं',
    'alert.issuedBy': 'द्वारा जारी',
    'alert.severity': 'गंभीरता',
    'alert.high': 'उच्च',
    'alert.medium': 'मध्यम',
    'alert.low': 'निम्न',
    'alert.description': 'विवरण',
    'alert.instructions': 'निर्देश',
    
    // Polls
    'polls.title': 'सामुदायिक पोल',
    'polls.subtitle': 'सामुदायिक निर्णयों में अपनी राय दें',
    'polls.active': 'सक्रिय',
    'polls.expired': 'समाप्त',
    'polls.closed': 'बंद',
    'polls.clickToVote': 'वोट करने के लिए एक विकल्प पर क्लिक करें',
    'polls.youVoted': '✓ आपने इस पोल पर वोट किया है',
    'polls.totalVotes': 'कुल वोट:',
    'polls.votes': 'वोट',
    'polls.endsIn': 'समाप्ति',
    'polls.expiresOn': 'समाप्ति तिथि',
    'polls.days': 'दिन',
    'polls.winner': 'विजेता',
    'polls.noActivePolls': 'फिलहाल कोई सक्रिय पोल नहीं',
    'polls.noExpiredPolls': 'कोई समाप्त पोल नहीं',
    
    // Profile
    'profile.title': 'प्रोफाइल',
    'profile.subtitle': 'अपने खाते और सेटिंग्स को प्रबंधित करें',
    'profile.yearsOld': 'साल की उम्र',
    'profile.address': 'पता',
    'profile.emergencyContacts': 'आपातकालीन संपर्क',
    'profile.volunteerInterests': 'स्वयंसेवक रुचियाँ',
    'profile.serviceProvided': 'प्रदान की गई सेवा',
    'profile.settings': 'सेटिंग्स',
    'profile.language': 'भाषा',
    'profile.changeLanguage': 'भाषा बदलें',
    'profile.aboutLegal': 'के बारे में और कानूनी',
    'profile.aboutMyArea': 'मायएरिया के बारे में',
    'profile.about': 'मायएरिया के बारे में',
    'profile.privacy': 'गोपनीयता नीति',
    'profile.terms': 'नियम और शर्तें',
    'profile.support': 'सहायता',
    'profile.helpSupport': 'मदद और सहायता',
    'profile.logout': 'लॉग आउट',
    'profile.logoutConfirm': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
    'profile.helpSupport': 'मदद और सहायता',
    'profile.faqs': 'अक्सर पूछे जाने वाले प्रश्न',
    'profile.logout': 'लॉग आउट',
    'profile.version': 'मायएरिया v1.0.0',
    
    // About Page
    'about.title': 'मायएरिया के बारे में',
    'about.whatIs': 'मायएरिया क्या है?',
    'about.description': 'मायएरिया एक सरकार समर्थित डिजिटल प्लेटफॉर्म है जो निवासियों को उनके स्थानीय समुदाय और नगर पालिका से जोड़ने के लिए डिज़ाइन किया गया है। एप्लिकेशन आपके वार्ड या सेक्टर के भीतर आधिकारिक नोटिस, आपातकालीन अलर्ट, सामुदायिक मदद, सत्यापित सेवाओं और स्वयंसेवक अवसरों तक पहुंच को सक्षम बनाता है।',
    'about.mission': 'हमारा मिशन',
    'about.missionDesc': 'मायएरिया का उद्देश्य सभी आयु वर्ग के नागरिकों के लिए सुरक्षा, पारदर्शिता और नागरिक भागीदारी में सुधार करना है।',
    'about.back': 'प्रोफाइल पर वापस जाएं',
    
    // Privacy Page
    'privacy.title': 'गोपनीयता नीति',
    'privacy.dataCollection': 'डेटा संग्रह',
    'privacy.dataCollectionDesc': 'हम केवल आवश्यक व्यक्तिगत जानकारी एकत्र करते हैं।',
    'privacy.dataUsage': 'डेटा उपयोग',
    'privacy.dataUsageDesc': 'डेटा का उपयोग केवल सामुदायिक सुरक्षा और सेवा वितरण के लिए किया जाता है।',
    'privacy.dataSharing': 'डेटा साझाकरण',
    'privacy.dataSharingDesc': 'कोई डेटा तीसरे पक्ष को नहीं बेचा जाता है।',
    'privacy.emergencyInfo': 'आपातकालीन जानकारी',
    'privacy.emergencyInfoDesc': 'आपातकालीन जानकारी केवल अलर्ट के दौरान साझा की जाती है।',
    'privacy.protection': 'डेटा सुरक्षा',
    'privacy.protectionDesc': 'सभी डेटा लागू डेटा सुरक्षा कानूनों के तहत संरक्षित है।',
    'privacy.back': 'प्रोफाइल पर वापस जाएं',
    
    // Terms Page
    'terms.title': 'नियम और शर्तें',
    'terms.accuracy': 'सटीकता',
    'terms.accuracyDesc': 'उपयोगकर्ताओं को सटीक जानकारी प्रदान करनी चाहिए।',
    'terms.misuse': 'दुरुपयोग',
    'terms.misuseDesc': 'SOS का दुरुपयोग या गलत अलर्ट निलंबन का कारण बन सकता है।',
    'terms.verification': 'सत्यापन',
    'terms.verificationDesc': 'नगर पालिका को खातों को सत्यापित या अस्वीकार करने का अधिकार है।',
    'terms.services': 'सेवाएं',
    'terms.servicesDesc': 'सूचीबद्ध सेवाएं समुदाय-प्रदत्त हैं, सरकारी गारंटी नहीं।',
    'terms.back': 'प्रोफाइल पर वापस जाएं',
    
    // Help & Support Page
    'helpSupport.title': 'मदद और सहायता',
    'helpSupport.faqs': 'अक्सर पूछे जाने वाले प्रश्न',
    'helpSupport.q1': 'सत्यापन में कितना समय लगता है?',
    'helpSupport.a1': 'आमतौर पर 1-2 व्यावसायिक दिन।',
    'helpSupport.q2': 'मेरी जानकारी कौन देख सकता है?',
    'helpSupport.a2': 'केवल आपात स्थिति के दौरान नगर पालिका प्रशासक और संबंधित समुदाय सदस्य।',
    'helpSupport.q3': 'क्या मैं बाद में अपनी भाषा बदल सकता हूं?',
    'helpSupport.a3': 'हाँ, प्रोफाइल → सेटिंग्स → भाषा बदलें से।',
    'helpSupport.q4': 'यदि मैं गलती से SOS दबा दूं तो क्या होगा?',
    'helpSupport.a4': 'भेजने से पहले आपको पुष्टि करने के लिए कहा जाएगा।',
    'helpSupport.q5': 'क्या सेवा प्रदाता सत्यापित हैं?',
    'helpSupport.a5': 'सेवाएं समुदाय-सूचीबद्ध हैं और मॉडरेशन के अधीन हैं।',
    'helpSupport.back': 'प्रोफाइल पर वापस जाएं',
    
    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'त्रुटि',
    'common.success': 'सफलता',
    'common.submit': 'सबमिट करें',
    'common.save': 'सहेजें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.confirm': 'पुष्टि करें',
    'common.back': 'वापस',
    'common.close': 'बंद करें',
    'common.ok': 'ठीक है',
    'common.or': 'या',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isLanguageSelected: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');
  const [isLanguageSelected, setIsLanguageSelected] = useState(false);

  useEffect(() => {
    const savedLanguage = localStorage.getItem('myarea_language') as Language;
    if (savedLanguage && ['en', 'ta', 'hi'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
      setIsLanguageSelected(true);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    setIsLanguageSelected(true);
    localStorage.setItem('myarea_language', lang);
  };

  const t = (key: string): string => {
    // First try to get translation for current language
    const translation = translations[language][key];
    if (translation) {
      return translation;
    }
    
    // Fallback to English
    const englishTranslation = translations['en'][key];
    if (englishTranslation) {
      console.warn(`Translation missing for key "${key}" in language "${language}", falling back to English`);
      return englishTranslation;
    }
    
    // If even English doesn't have it, log error and return key
    console.error(`Translation missing for key "${key}" in all languages`);
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isLanguageSelected }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
